### PR TITLE
Condensing docs and removing numbering from folder/category names

### PR DESCRIPTION
**Pull request by MitThomas**
Condensing docs: Merged numerous small markdown docs into a smaller number of larger documents.

Removing numbering from folder/category names, made the names kebab case.

### CODE REVIEW

**Review by elepner — CHANGES_REQUESTED** [review]
The project does not build, description for __category.json__ cannot be empty. Link description is used when category is opened directly.
image
image
In VSCode go to search panel, type ``"description": ""`` and fix all the issues.

**Comment by elepner** [comment]
description might be empty, but in this case you need to remove the field entirely.

**Comment by elepner** [comment]
``Dimension Input Panel.md`` has broken reference to the ``Using_the_dimension_input_panel.png`` image.

**Comment by MitThomas** [comment]
Thanks @elepner, they should be resolved now.

**Pull request merged**
